Tier.Gui/Controllers/ComercialController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tier.Gui.Controllers
{
    public partial class ComercialController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="idPeriodo"></param>
        /// <param name="arrProductos"></param>
        /// <param name="costoTotalPlachas"></param>
        /// <param name="costoTotalTroqueles"></param>
        private static void CalcularCostoPlanchasTroqueles(int idPeriodo, int[] arrProductos, ref Single costoTotalPlachas, ref Single costoTotalTroqueles)
        {
            int cantTintas = 0;
            Single costoPlancha = 0;

            foreach (var item in arrProductos)
            {
                CotizarService.Producto objProd = SAL.Productos.RecuperarXId(item, true);

                if (objProd != null && objProd.nuevo.HasValue && objProd.nuevo == true)
                {

                    if (objProd.maquinavariprod_idVariacion_rutalitografia.HasValue)
                    {
                        CotizarService.Maquina objMaquina = SAL.Maquinas.RecuperarXIdRutaProduccion((int)objProd.maquinavariprod_idVariacion_rutalitografia, true);

                        cantTintas = objProd.espectro.Count;
                        costoPlancha = (objMaquina != null && objMaquina.valorplancha.HasValue ? (Single)objMaquina.valorplancha : 0);
                    }

                    Single costoTroquel = 0;

                    var lstProdTroq = SAL.Productos.RecuperarFiltrados(new CotizarService.Producto() { troquel_idtroquel = objProd.troquel_idtroquel }, false);
                    if (lstProdTroq.Count() <= 1)
                    {
                        costoTroquel = objProd.costotroquel.HasValue ? objProd.costotroquel.Value : 0;
                    }

                    costoTotalTroqueles += costoTroquel;
                    costoTotalPlachas += (cantTintas * costoPlancha);
                }
            }
        }

    }
}

Tier.Gui/Controllers/ProduccionController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Text;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tier.Gui.Controllers
{
    public partial class ProduccionController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Tier.Gui/Views/Comercial/Cartera.cshtml
@{
    ViewBag.Title = "Cartera";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--Listar-->
<div class="col-md-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Gestión de cartera en mora</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a href="@Url.Action("ActualizarCartera", "Comercial" )"><i class="fa fa-file-excel-o"></i> Actualizar</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Home" )"><i class="fa fa-close"></i> Cerrar</a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">

        </div>
    </div>
</div>

<script>
    $("#").DataTable();
</script>

Tier.Gui/Views/Comercial/CrearCotizacion.cshtml
@model Tier.Gui.CotizarService.CotizacionModelo
@{
    ViewBag.Title = "CrearCotizacion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    Tier.Gui.CotizarService.Cliente objCliente = (Tier.Gui.CotizarService.Cliente)ViewBag.Cliente;
}
<div class="col-md-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Nueva cotización</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a href="@Url.Action("ListaCotizaciones", "Comercial", new { id = objCliente.idcliente }, null)"><i class="fa fa-close"></i> Cerrar</a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            @using (Html.BeginForm("CrearCotizacion", "Comercial", null, FormMethod.Post, new { @class = "form-horizontal form-label-left", onsubmit = "Comercial.HabilitaCampos();" }))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("editando", true)
                @Html.Hidden("activo", true)
                @Html.Hidden("hdfProdCotizar", "", new { data_val = "true", data_val_required = "Dato requerido." })
                @Html.Hidden("cliente_idcliente", objCliente.idcliente)
                @Html.HiddenFor(model => model.costosplancha)
                @Html.HiddenFor(model => model.costostroqueles)

                <div class="form-group">
                    <div class="col-xs-12 invoice-header">
                        <h1>
                            <i class="fa fa-building"></i> @objCliente.nombre
                        </h1>
                    </div>
                    <div class="row invoice-info">
                        <div class="col-sm-12 invoice-col">
                            <address>
                                <strong>Identificación:&nbsp;</strong>@objCliente.identificacion
                                <strong>Dirección:&nbsp;</strong> @objCliente.direccion
                                <strong>Ciudad:&nbsp;</strong> @objCliente.municipio_desmunicipio
                                <strong>Departamento:&nbsp;</strong> @objCliente.municipio_departamento_descdepartamento
                            </address>
                        </div>
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-2 col-sm-2 col-xs-12 form-group">
                        @Html.DropDownListFor(model => model.periodo_idPeriodo, null, " -- Periodo -- ", new { @class = "form-control has-feedback-left", data_val = "true", data_val_required = "Dato requerido." })
                        @Html.ValidationMessageFor(model => model.periodo_idPeriodo)
                        <span class="fa fa-puzzle-piece form-control-feedback left" aria-hidden="true"></span>
                    </div>
                    <button type="button" class="btn btn-success" data-toggle="modal" data-target=".bs-example-modal-sm1">
                        <i class="fa fa-plus"></i>
                        Adicionar Producto
                    </button>
                </div>
                <div class="form-group">
                    <div id="contProductosCotizacion">
                        <table id="tblProductosCotizacion">
                            <thead></thead>
                            <tbody></tbody>
                        </table>
                    </div>
                    <div id="sinProductosMsj">
                        <div style="width: 80%;text-align:center;margin: 0 auto;font-size: smaller;color: darkorange;">
                            <p>
                                <span class="glyphicon glyphicon-alert" aria-hidden="true" style="font-size: 32px;"></span>
                            </p><span>No se han ingresado productos en la cotización</span>
                        </div>
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                        @Html.TextAreaFor(model => model.observaciones, new { @class = "form-control has-feedback-left", placeholder = "Observaciones generales" })
                    </div>
                    <div class="col-md-4 col-sm-12 col-xs-12 text-right">
                        <table class="pull-right" style="margin-right:11px;">
                            <tr>
                                <th style="text-align:right;">@Html.LabelFor(model => model.costosplancha):&nbsp;$&nbsp;</th>
                                <td style="text-align:right;"><label id="lblcostosplancha">0</label></td>
                            </tr>
                            <tr>
                                <th style="text-align:right;">@Html.LabelFor(model => model.costostroqueles):&nbsp;$&nbsp;</th>
                                <td style="text-align:right;"><label id="lblcostostroqueles">0</label></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-12">
                        <div>
                            <input type="submit" name="btnGuardar" id="btnGuardar" class="btn btn-success btn-lg" value="Guardar" />
                        </div>
                        <div class="label label-warning">
                            <span>ADVERTENCIA: La cotización no puede ser editada después de ser creada.</span>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@*Modal para la adición de productos a la cotización*@
<div tabindex="-1" class="modal fade bs-example-modal-sm1" role="dialog" aria-hidden="true" style="display: none" data-backdrop="static">
    <div class="modal-dialog" style=" max-width: 600px;">
        <div class="modal-content">
            <form action="" method="post" id="frmNwProdCotizacion">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Adicionar producto</h4>
                </div>
                <div class="modal-body">
                    @Html.Hidden("guidProductoCotizar")
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
                                @Html.Label("Seleccione producto: ")
                                @Html.DropDownList("producto_idproducto", null, " -- Producto -- ", new { @class = "form-control has-feedback-left", data_val = "true", data_val_required = "Dato requerido", onchange = "Comercial.ObtenerImagenProducto();" })
                                <span class="field-validation-valid" data-valmsg-for="nombreProvLinea" data-valmsg-replace="true"></span>
                                <span class="fa fa-archive form-control-feedback left" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
                                @Html.Label("Ciudad destino: ")
                                @Html.DropDownList("insumo_idinsumo_flete", (SelectList)ViewBag.insumo_idinsumo_flete, " -- Flete -- ", new { @class = "form-control has-feedback-left", data_val = "true", data_val_required = "Dato requerido" })
                                <span class="field-validation-valid" data-valmsg-for="nombreProvLinea" data-valmsg-replace="true"></span>
                                <span class="fa fa-truck form-control-feedback left" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
                                @Html.Label("Observación: ")
                                @Html.TextArea("comentarioAdicional", "", new { @class = "form-control has-feedback-left", placeholder = "Comentarios adicionales" })
                                <span class="field-validation-valid" data-valmsg-for="nombreProvLinea" data-valmsg-replace="true"></span>
                                <span class="fa fa-info form-control-feedback left" aria-hidden="true"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="contImgProdCotizar">
                                <img id="imgProdCotizarMdl" src="~/images/Imagen_no_disponible.png" data-scrnotfoung="@Url.Content("~/images/Imagen_no_disponible.png")" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" onclick="Comercial.AgregarProdCotizar();">Cotizar</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@*Modal para el detalle del valor de las escalas*@
<div tabindex="-2" class="modal fade bs-example-modal-sm2" role="dialog" aria-hidden="true" style="display: none" data-backdrop="static">
    <div class="modal-dialog" style=" max-width: 600px;">
        <div class="modal-content">
            <form action="" method="post" id="frmDetalleProdCotizacionEscala">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Detalle valores costo</h4>
                </div>
                <div id="trgCotProDetEscala" class="modal-body"></div>
                <div class="col-md-12">
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@*Modal para el detalle del producto*@
<div tabindex="-3" class="modal fade bs-example-modal-sm3" role="dialog" aria-hidden="true" style="display: none" data-backdrop="static">
    <div class="modal-dialog" style=" max-width: 600px;">
        <div class="modal-content">
            <form action="" method="post" id="frmDetalleProdCotizacion">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Detalle producto</h4>
                </div>
                <div id="trgCotProDet" class="modal-body"></div>
                <div class="col-md-12">
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                        @Html.ActionLink("Editar producto", "EditarProducto", "Produccion", new { id = 0 }, new { @class = "btn btn-success", id = "btnEditarProd", name = "btnEditarProd" })
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.bs-example-modal-sm1').on('hidden.bs.modal', function (e) {
            Comercial.RestaurarModalProdCotizar();
        });

        $('.bs-example-modal-sm1').on('show.bs.modal', function (e) {
            if ($("#periodo_idPeriodo").val() == null || $("#periodo_idPeriodo").val() == "") {
                new PNotify({
                    title: 'Debe seleccionar un periodo',
                    text: '',
                    type: 'error'
                });
                return false;
            }
        });

        $("#costosplancha").val(0);
        $("#costostroqueles").val(0);

        NProgress.done();
    });
</script>

Tier.Gui/Views/Comercial/ListaAsesores.cshtml
@model IEnumerable<Tier.Gui.CotizarService.Asesor>

@{
    ViewBag.Title = "ListaAsesores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Gestión de asesores</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a href="@Url.Action("CrearAsesor", "Comercial")"><i class="fa fa-plus"></i> Crear</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-close"></i> Cerrar</a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div id="divFiltros">
                @using (Ajax.BeginForm("ListaAsesores", "Comercial", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divTabla", }))
                {
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-6 form-group has-feedback">
                            @Html.TextBox("txtNombre", null, new { @class = "form-control has-feedback-left", placeholder = "Nombre", data_val = "true", data_val_length = "El campo acepta mínimo 3, máximo 256 caracteres", data_val_length_min = "3", data_val_length_max = "256" })
                            @Html.ValidationMessage("txtNombre")
                            <span class="fa fa-eye form-control-feedback left" aria-hidden="true"></span>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6 form-group has-feedback">
                            @Html.TextBox("txtCodigo", null, new { @class = "form-control has-feedback-left", placeholder = "Código", data_val = "true", data_val_length = "El campo acepta mínimo 2, máximo 16 caracteres", data_val_length_min = "2", data_val_length_max = "16" })
                            @Html.ValidationMessage("txtCodigo")
                            <span class="fa fa-crosshairs form-control-feedback left" aria-hidden="true"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
                            <input class="btn btn-primary pull-right" type="reset" value="Limpiar" />
                            <button class="btn btn-success pull-right" onclick="NProgress.start();"><i class="fa fa-binoculars"></i> Buscar</button>
                        </div>
                    </div>
                }
            </div>
            <div class="clearfix"></div>
            <hr />
            <div id="divTabla">
                <div style="width: 80%;text-align:center;margin: 0 auto;font-size: smaller;color: darkorange;"><p><span class="glyphicon glyphicon-search" aria-hidden="true" style="font-size: 32px;"></span></p><span>Por favor realice una búsqueda para mostrar los resultados</span></div>
            </div>
        </div>
    </div>
</div>

Tier.Gui/Views/Comercial/ListaClientes.cshtml
@{
    ViewBag.Title = "ListaClientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Gestión de clientes</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a href="@Url.Action("CrearCliente", "Comercial")"><i class="fa fa-plus"></i> Crear</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-close"></i> Cerrar</a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div id="divFiltros">
                @using (Ajax.BeginForm("ListaClientes", "Comercial", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divTabla", }))
                {
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
                            @Html.TextBox("txtRazonSocial", null, new { @class = "form-control has-feedback-left", placeholder = "Razón social", data_val = "true", data_val_length = "El campo acepta mínimo 3, máximo 512 caracteres", data_val_length_min = "3", data_val_length_max = "512" })
                            @Html.ValidationMessage("txtRazonSocial")
                            <span class="fa fa-eye form-control-feedback left" aria-hidden="true"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-6 form-group has-feedback">
                            @Html.TextBox("txtIdentificacion", null, new { @class = "form-control has-feedback-left", placeholder = "Identificación", data_val = "true", data_val_length = "El campo acepta mínimo 3, máximo 16 caracteres", data_val_length_min = "3", data_val_length_max = "16" })
                            @Html.ValidationMessage("txtIdentificacion")
                            <span class="fa fa-crosshairs form-control-feedback left" aria-hidden="true"></span>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6 form-group has-feedback">
                            @Html.DropDownList("ddlAsesor", (SelectList)ViewBag.ddlAsesor, " -- Asesor -- ", new { @class = "form-control has-feedback-left" })
                            @Html.ValidationMessage("ddlAsesor")
                            <span class="fa fa-tag form-control-feedback left" aria-hidden="true"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
                            <input class="btn btn-primary pull-right" type="reset" value="Limpiar" />
                            <button class="btn btn-success pull-right" onclick="NProgress.start();"><i class="fa fa-binoculars"></i> Buscar</button>
                        </div>
                    </div>
                }
            </div>
            <div class="clearfix"></div>
            <hr />
            <div id="divTabla">
                <div style="width: 80%;text-align:center;margin: 0 auto;font-size: smaller;color: darkorange;"><p><span class="glyphicon glyphicon-search" aria-hidden="true" style="font-size: 32px;"></span></p><span>Por favor realice una búsqueda para mostrar los resultados</span></div>
            </div>
        </div>
    </div>
</div>

Tier.Gui/Views/Comercial/_TablaAsesores.cshtml
@model IEnumerable<Tier.Gui.CotizarService.Asesor>

<script>
    NProgress.start();
</script>

<table id="tblAsesores">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.comision)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.correoelectronico)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.activo)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <ul class="nav nav-pills" role="tablist">
                        <li role="presentation" class="dropdown">
                            <a id="drop4" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="true">
                                <span class="fa fa-chevron-down"></span>
                            </a><div class="dropdown-backdrop"></div>
                            <ul id="menu6" class="dropdown-menu animated fadeInDown" role="menu">
                                <li role="presentation">
                                    @Html.ActionLink("Modificar", "EditarAsesor", "Comercial", new { id = item.idasesor }, null)
                                </li>
                                <li role="presentation" class="divider"></li>
                                <li role="presentation">
                                    @Html.ActionLink("Eliminar", "EliminarAsesor", "Comercial", new { id = item.idasesor }, null)
                                </li>
                            </ul>
                        </li>
                    </ul>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.comision, "PercentNumber")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.telefono)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.correoelectronico)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.activo)
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    $("#tblAsesores").DataTable();
</script>

<script>
    NProgress.done();
</script>

Tier.Gui/Views/Comercial/_TablaClientes.cshtml
@model IEnumerable<Tier.Gui.CotizarService.Cliente>

<script>
    NProgress.start();
</script>

<table id="tblClientes">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.identificacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.itemlista_iditemlista_tipoidenti)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.municipio_idmunicipio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.asesor_idasesor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nuevo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.activo)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <ul class="nav nav-pills" role="tablist">
                        <li role="presentation" class="dropdown">
                            <a id="drop4" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="true">
                                <span class="fa fa-chevron-down"></span>
                            </a><div class="dropdown-backdrop"></div>
                            <ul id="menu6" class="dropdown-menu animated fadeInDown" role="menu">
                                <li role="presentation">
                                    @Html.ActionLink("Modificar", "EditarCliente", "Comercial", new { id = item.idcliente }, null)
                                </li>
                                <li role="presentation">
                                    @Html.ActionLink("Ver contactos", "ContactosCliente", "Comercial", new { id = item.idcliente }, null)
                                </li>
                                <li role="presentation" class="divider">
                                </li>
                                <li role="presentation">
                                    @Html.ActionLink("Crear cotización", "CrearCotizacion", "Comercial", new { id = item.idcliente }, null)
                                </li>
                                <li role="presentation">
                                    @Html.ActionLink("Ver cotizaciones", "ListaCotizaciones", "Comercial", new { id = item.idcliente }, null)
                                </li>
                                <li role="presentation">
                                    @Html.ActionLink("Ver pedidos", "ListaPedidos", "Comercial", new { id = item.idcliente }, null)
                                </li>
                                <li role="presentation" class="divider"></li>
                                <li role="presentation">
                                    @Html.ActionLink("Crear producto", "CrearProducto", "Produccion", new { id = item.idcliente }, null)
                                </li>
                                <li role="presentation">
                                    @Html.ActionLink("Ver productos", "ListaProductos", "Produccion", new { id = item.idcliente }, null)
                                </li>
                                <li role="presentation" class="divider"></li>
                                <li role="presentation">
                                    @Html.ActionLink("Eliminar", "EliminarCliente", "Comercial", new { id = item.idcliente }, null)
                                </li>
                            </ul>
                        </li>
                    </ul>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.identificacion)
                </td>
                <td>
                    @if (string.IsNullOrEmpty(item.itemlista_iditemlista_desctipoidenti))
                    {
                        <text>N/A</text>
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.itemlista_iditemlista_desctipoidenti)
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.direccion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.municipio_desmunicipio)
                </td>
                <td>
                    @if (string.IsNullOrEmpty(item.asesor_descasesor))
                    {
                        <text>N/A</text>
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.asesor_descasesor)
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nuevo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.activo)
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    $("#tblClientes").DataTable();
</script>

<script>
    NProgress.done();
</script>