Tier.Gui/Controllers/AdministracionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using Newtonsoft.Json.Schema;
using System.Globalization;
using System.Text;

namespace Tier.Gui.Controllers
{
    public partial class AdministracionController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Tier.Gui/Views/Administracion/CrearEmpresa.cshtml
@model Tier.Gui.CotizarService.EmpresaModel

@{
    ViewBag.Title = "Crear-Empresa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Nueva empresa</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a href="@Url.Action("ListaEmpresas", "Administracion")"><i class="fa fa-close"></i> Cerrar</a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            @using (Html.BeginForm("CrearEmpresa", "Administracion", null, FormMethod.Post, new { @class = "form-horizontal form-label-left", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("activo", true)
                
                <div class="form-group">
                    @Html.LabelFor(model => model.razonsocial, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.razonsocial, new { @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.razonsocial)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.nit, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.nit, new { @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.nit)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.direccion, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.direccion, new { @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.direccion)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.telefono, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.telefono, new { @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.telefono)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.representantelegal, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.representantelegal, new { @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.representantelegal)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ImageUpload, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.EditorFor(m => m.ImageUpload)
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="submit" name="btnGuardar" id="btnGuardar" class="btn btn-success" value="Guardar" />
                        <button type="reset" class="btn btn-primary">Limpiar</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Tier.Gui/Views/Administracion/CrearPeriodo.cshtml
@model Tier.Gui.CotizarService.PeriodoModel

@{
    ViewBag.Title = "CrearPeriodo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Nuevo período</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a href="@Url.Action("ListaPeriodos", "Administracion" )"><i class="fa fa-close"></i> Cerrar</a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            @using (Html.BeginForm("CrearPeriodo", "Administracion", null, FormMethod.Post, new { @class = "form-horizontal form-label-left", id = "frmCrearPeriodo" }))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("editando", false)
                @Html.Hidden("nombreinicial", null)

                <div class="form_wizard wizard_horizontal" id="wizard">
                    @*Cabeceras Secciones*@
                    <ul class="wizard_steps anchor">
                        <li>
                            <a class="selected" href="#step-1" rel="1" isdone="1">
                                <span class="step_no">1</span>
                                <span class="step_descr">
                                    Paso 1<br>
                                    <small>Datos básicos</small>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="disabled" href="#step-2" rel="2" isdone="0">
                                <span class="step_no">2</span>
                                <span class="step_descr">
                                    Paso 2<br>
                                    <small>Datos centros</small>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="disabled" href="#step-3" rel="3" isdone="0">
                                <span class="step_no">3</span>
                                <span class="step_descr">
                                    Paso 3<br>
                                    <small>Datos parámetros</small>
                                </span>
                            </a>
                        </li>
                    </ul>
                    @*Contenedores*@
                    <div class="stepContainer">
                        <div class="wizard_content" id="step-1" style="display: block;">
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-6 form-group has-feedback cursorno-drop">
                                    @Html.DropDownListFor(model => model.empresa_idempresa, null, " -- Empresa -- ", new { @class = "form-control has-feedback-left empresaSL" })
                                    @Html.ValidationMessageFor(model => model.empresa_idempresa)
                                    <span class="fa fa-building form-control-feedback left" aria-hidden="true"></span>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6 form-group has-feedback cursorno-drop">
                                    @Html.TextBoxFor(model => model.nombre, new { @class = "form-control has-feedback-left", placeholder = "Nombre" })
                                    @Html.ValidationMessageFor(model => model.nombre)
                                    <span class="fa fa-eye form-control-feedback left" aria-hidden="true"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                                    @Html.LabelFor(model => model.fechainicio, new { @class = "control-label col-md-4 col-sm-3 col-xs-12" })
                                    <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                                        @Html.TextBoxFor(model => model.fechainicio, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.fechainicio)
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                                    @Html.LabelFor(model => model.fechafin, new { @class = "control-label col-md-4 col-sm-3 col-xs-12" })
                                    <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                                        @Html.TextBoxFor(model => model.fechafin, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.fechafin)
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-6 form-group">
                                    @Html.LabelFor(model => model.gasto, new { @class = "control-label col-md-4 col-sm-3 col-xs-12" })
                                    <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                                        @Html.TextBoxFor(model => model.gasto, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.gasto)
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                                    @Html.LabelFor(model => model.utilidad, new { @class = "control-label col-md-4 col-sm-3 col-xs-12" })
                                    <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                                        @Html.TextBoxFor(model => model.utilidad, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.utilidad)
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-6 form-group">
                                    @Html.LabelFor(model => model.porcenfinanciacion, new { @class = "control-label col-md-4 col-sm-3 col-xs-12" })
                                    <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                                        @Html.TextBoxFor(model => model.porcenfinanciacion, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.porcenfinanciacion)
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                                    @Html.LabelFor(model => model.porcenalzageneral, new { @class = "control-label col-md-4 col-sm-3 col-xs-12" })
                                    <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                                        @Html.TextBoxFor(model => model.porcenalzageneral, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.porcenalzageneral)
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                                    @Html.LabelFor(model => model.impuestoicacree, new { @class = "control-label col-md-4 col-sm-3 col-xs-12" })
                                    <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                                        @Html.TextBoxFor(model => model.impuestoicacree, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.impuestoicacree)
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="stepContainer">
                        <div class="wizard_content" id="step-2" style="display: block;">
                            @Html.HiddenFor(model => model.hfdcentros)
                            <div class="x_content pericentros"></div>
                        </div>
                    </div>
                    <div class="stepContainer">
                        <div class="wizard_content" id="step-3" style="display: block;">
                            @Html.HiddenFor(model => model.hfdparametros)
                            <div class="x_content periparams"></div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        // Smart Wizard
        $('#wizard').smartWizard({
            labelNext: 'Siguiente', // label for Next button
            labelPrevious: 'Anterior', // label for Previous button
            labelFinish: 'Terminar',  // label for Finish button
            keyNavigation: false,
            onLeaveStep: leaveAStepCallback,
            onFinish: finishCallback,
        });

        function finishCallback() {
            if ($('#frmCrearPeriodo').valid()) {
                $('#frmCrearPeriodo').submit();
            }
            else {
                new PNotify({
                    title: 'Advertencia!',
                    text: 'Algunos valores no son validos. Por favor revise e intente nuevamente.',
                    type: 'error'
                });

                return false;
            }
        }

        function leaveAStepCallback() {
            if (!$('#frmCrearPeriodo').valid()) {
                new PNotify({
                    title: 'Advertencia!',
                    text: 'Algunos valores no son validos. Por favor revise e intente nuevamente.',
                    type: 'error'
                });

                return false;
            }
            else {
                return true;
            }
        }

        $('#fechainicio').daterangepicker({
            //format: 'DD/MM/YYYY',
            singleDatePicker: true,
            showDropdowns: true,
            calender_style: "picker_2"
        }, function (start, end, label) {
            $('#fechainicio').change();
        });

        $('#fechafin').daterangepicker({
            //format: 'DD/MM/YYYY',
            singleDatePicker: true,
            showDropdowns: true,
            calender_style: "picker_2"
        }, function (start, end, label) {
            $('#fechafin').change();
        });
    });
</script>

@if (ViewBag.ParametrosPredefinidos != null)
{
    <script type="text/javascript">
        $(document).ready(function () {
            var arrParametros = JSON.parse(String('@Html.Raw(ViewBag.ParametrosPredefinidos)'));

            Administracion.CargarJsonParametros(arrParametros);
            Administracion.CargarTablaParametros(arrParametros);
            Administracion.AsignarValorCamposParametros(arrParametros);
        });
    </script>
}

@if (ViewBag.MaquinasActivas != null)
{
    <script type="text/javascript">
        $(document).ready(function () {
            var arrMaquinasActivas = JSON.parse(String('@Html.Raw(ViewBag.MaquinasActivas)'));

            Administracion.CargarJsonCentrosMaquinas(arrMaquinasActivas);
            Administracion.CargarTablaCentrosMaquinas(arrMaquinasActivas);
            Administracion.AsignarValorCamposCentrosMaquinas(arrMaquinasActivas);
        });
    </script>
}

Tier.Gui/Views/Administracion/CrearRol.cshtml
@model Tier.Gui.CotizarService.RolModel

@{
    ViewBag.Title = "CrearRol";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Nuevo rol</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a href="@Url.Action("ListaRoles", "Administracion")"><i class="fa fa-close"></i> Cerrar</a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            @using (Html.BeginForm("CrearRol", "Administracion", null, FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(ee => ee.hfdPermisosSeleccionados)
                @Html.Hidden("editando", false)
                @Html.Hidden("nombreinicial", null)
                
                <div class="form-group">
                    <div class="col-md-4 col-sm-12 col-xs-12 form-group has-feedback">
                        @Html.TextBoxFor(model => model.nombre, new { @class = "form-control has-feedback-left", placeholder = "Nombre" })
                        @Html.ValidationMessageFor(model => model.nombre)
                        <span class="fa fa-paw form-control-feedback left" aria-hidden="true"></span>
                    </div>
                    <div class="col-md-8 col-sm-142 col-xs-12 form-group has-feedback">
                        @Html.TextBoxFor(model => model.descripcion, new { @class = "form-control has-feedback-left", placeholder = "Descripción" })
                        @Html.ValidationMessageFor(model => model.descripcion)
                        <span class="fa fa-quote-right form-control-feedback left" aria-hidden="true"></span>
                    </div>
                </div>
                @Html.Partial("_RolFuncionalidades", (IEnumerable<Tier.Gui.CotizarService.Funcionalidad>)ViewBag.lstFuncionalidades)
                <div class="clearfix"></div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="submit" name="btnGuardar" id="btnGuardar" class="btn btn-success" value="Guardar" />
                        <button type="reset" class="btn btn-primary">Limpiar</button>

                        <button class="btn btn-round btn-default navbar-right" type="button" onclick="Administracion.DesmarcarTodosPermidos();">Desmarcar todos</button>
                        <button class="btn btn-round btn-default navbar-right" type="button" onclick="Administracion.MarcarTodosPermidos();">Marcar todos</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Tier.Gui/Views/Administracion/CrearUsuario.cshtml
@model Tier.Gui.CotizarService.Usuario

@{
    ViewBag.Title = "CrearUsuario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Nueva usuario</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a href="@Url.Action("ListaUsuarios", "Administracion")"><i class="fa fa-close"></i> Cerrar</a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            @using (Html.BeginForm("CrearUsuario", "Administracion", null, FormMethod.Post, new { @class = "form-horizontal form-label-left", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("editando", false)
                @Html.Hidden("usuarioinicial", null)
                
                <div class="form-group">
                    <div class="col-md-4 col-sm-12 col-xs-12 form-group has-feedback">
                        @Html.TextBoxFor(model => model.usuario, new { @class = "form-control has-feedback-left", placeholder = "Alias" })
                        @Html.ValidationMessageFor(model => model.usuario)
                        <span class="fa fa-paw form-control-feedback left" aria-hidden="true"></span>
                    </div>
                    <div class="col-md-4 col-sm-12 col-xs-12 form-group has-feedback">
                        @Html.DropDownListFor(model => model.rol_idrol, (SelectList)ViewBag.lstRoles, " -- Rol --", new { @class = "form-control has-feedback-left" })
                        @Html.ValidationMessageFor(model => model.rol_idrol)
                        <span class="fa fa-users form-control-feedback left" aria-hidden="true"></span>
                    </div>
                    <div class="col-md-4 col-sm-12 col-xs-12 form-group has-feedback">
                        @Html.DropDownListFor(model => model.empresa_idempresa, (SelectList)ViewBag.lstEmpresas, " -- Empresa --", new { @class = "form-control has-feedback-left" })
                        @Html.ValidationMessageFor(model => model.empresa_idempresa)
                        <span class="fa fa-building form-control-feedback left" aria-hidden="true"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-sm-12 col-xs-12 form-group">
                        @Html.LabelFor(model => model.nombrecompleto, new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                        <div class="col-md-9 col-sm-12 col-xs-12 form-group">
                            @Html.TextBoxFor(model => model.nombrecompleto, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.nombrecompleto)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-sm-12 col-xs-12 form-group">
                        @Html.LabelFor(model => model.correoelectronico, new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                        <div class="col-md-9 col-sm-12 col-xs-12 form-group">
                            @Html.TextBoxFor(model => model.correoelectronico, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.correoelectronico)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-sm-12 col-xs-12 form-group">
                        @Html.LabelFor(model => model.celular, new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                        <div class="col-md-9 col-sm-12 col-xs-12 form-group">
                            @Html.TextBoxFor(model => model.celular, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.celular)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-sm-12 col-xs-12 form-group">
                        @Html.LabelFor(model => model.cargo, new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                        <div class="col-md-9 col-sm-12 col-xs-12 form-group">
                            @Html.TextBoxFor(model => model.cargo, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.cargo)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-sm-12 col-xs-12 form-group">
                        @Html.LabelFor(model => model.itemlista_iditemlistas_area, new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                        <div class="col-md-9 col-sm-12 col-xs-12 form-group">
                            @Html.DropDownListFor(model => model.itemlista_iditemlistas_area, (SelectList)ViewBag.lstAreas, " -- Área -- ", new { @class = "form-control", data_val = "true", data_val_required = "Dato requerido." })
                            @Html.ValidationMessageFor(model => model.itemlista_iditemlistas_area)
                        </div>
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="submit" name="btnGuardar" id="btnGuardar" class="btn btn-success" value="Guardar" />
                        <button type="reset" class="btn btn-primary">Limpiar</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Tier.Gui/Views/Administracion/EditarEmpresa.cshtml
@model Tier.Gui.CotizarService.EmpresaModel

@{
    ViewBag.Title = "EditarEmpresa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Modificar empresa</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a href="@Url.Action("ListaEmpresas", "Administracion")"><i class="fa fa-close"></i> Cerrar</a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            @using (Html.BeginForm("EditarEmpresa", "Administracion", null, FormMethod.Post, new { @class = "form-horizontal form-label-left", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("editando", true)
                @Html.Hidden("idempresa", Model.idempresa)
                @Html.Hidden("urilogo", Model.urilogo)

                <div class="form-group">
                    @Html.LabelFor(model => model.razonsocial, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.razonsocial, new { @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.razonsocial)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.nit, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.nit, new { @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.nit)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.direccion, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.direccion, new { @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.direccion)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.telefono, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.telefono, new { @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.telefono)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.representantelegal, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.representantelegal, new { @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.representantelegal)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ImageUpload, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.EditorFor(m => m.ImageUpload)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.activo, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                        @Html.CheckBox("activo", Model.activo.Value)
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="submit" name="btnGuardar" id="btnGuardar" class="btn btn-success" value="Guardar" />
                        <button type="reset" class="btn btn-primary">Limpiar</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Tier.Gui/Views/Administracion/ListaEmpresas.cshtml
@model IEnumerable<Tier.Gui.CotizarService.Empresa>

@{
    ViewBag.Title = "ListaEmpresas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Gestión de empresas</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a href="@Url.Action("CrearEmpresa", "Administracion")"><i class="fa fa-plus"></i> Crear</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-close"></i> Cerrar</a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            @Html.Partial("_TablaEmpresas", Model)
        </div>
    </div>
</div>